/* Auto-generated by frap_table_generator.py */
#pragma once

#include <stdint.h>

struct frap_cfg_entry {
    const char *name; /* task name / label */
    int resid;
    int spin_prio; /* numeric priority */
    int pid_hint; /* optional hint used by demo */
};

static const struct frap_cfg_entry frap_generated_table[] = {
    { "w00", 0, 200, 0 },
    { "w01", 0, 200, 1 },
    { "w02", 0, 200, 2 },
    { "w03", 0, 200, 3 },
    { "w04", 0, 200, 4 },
    { "w05", 0, 200, 5 },
    { "w06", 0, 200, 6 },
    { "w07", 0, 200, 7 },
    { "w08", 0, 200, 8 },
    { "w09", 0, 200, 9 },
    { "w10", 0, 200, 10 },
    { "w11", 0, 200, 11 },
};

static const int frap_generated_table_len = sizeof(frap_generated_table)/sizeof(frap_generated_table[0]);
