/* Auto-generated by frap_table_generator.py */
#pragma once

#include <stdint.h>

struct frap_cfg_entry {
    const char *name; /* task name / label */
    int resid;
    int spin_prio; /* numeric priority */
    int pid_hint; /* optional hint used by demo */
};

static const struct frap_cfg_entry frap_generated_table[] = {
    { "hot0", 0, 250, 0 },
    { "hot0", 1, 250, 0 },
    { "hot0", 4, 250, 0 },
    { "hot1", 0, 238, 1 },
    { "hot1", 1, 250, 1 },
    { "hot1", 5, 250, 1 },
    { "hot2", 0, 236, 2 },
    { "hot2", 2, 250, 2 },
    { "hot2", 4, 236, 2 },
    { "mid0", 2, 200, 3 },
    { "mid0", 3, 250, 3 },
    { "mid0", 6, 250, 3 },
    { "mid1", 3, 190, 4 },
    { "mid1", 7, 199, 4 },
    { "remoteA0", 1, 250, 5 },
    { "remoteA0", 3, 250, 5 },
    { "remoteA0", 5, 250, 5 },
    { "remoteA1", 1, 250, 6 },
    { "remoteA1", 4, 250, 6 },
    { "remoteA2", 2, 250, 7 },
    { "remoteA2", 6, 250, 7 },
    { "remoteB0", 1, 250, 8 },
    { "remoteB0", 7, 250, 8 },
    { "remoteB1", 0, 250, 9 },
    { "remoteB1", 3, 250, 9 },
    { "background0", 7, 250, 10 },
    { "background1", 5, 250, 11 },
    { "background1", 6, 250, 11 },
};

static const int frap_generated_table_len = sizeof(frap_generated_table)/sizeof(frap_generated_table[0]);
